language: node_js
os: linux
sudo: false
cache: 
  - directories:
    - node_modules
node_js:
- '12'
- '11'
- '10'
stages:
  - install
  - lint
  - test
  - deploy
jobs:
  include:
    - stage: install
      script: npm ci
    - stage: lint
      script: npm run lint-check
    - stage: test
      script: npm test
    - stage: deploy
      script:
        - echo "Not yet"     


